version: "3.7"
services:
  aws-auth-cli:
    environment:
      - GOOGLE_IDP_ID
      - GOOGLE_SP_ID
    volumes:
      - ~/:/root
    build:
      context: ./cli
      dockerfile: Dockerfile
    container_name: aws-auth-cli

  aws-auth-console:
    environment:
      - FLAG_HERE
    volumes:
      - ~/:/root
    build:
      context: ./console
      dockerfile: Dockerfile
    container_name: aws-auth-console
